# Generated by Django 3.2.15 on 2023-09-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre_Persona', models.TextField(max_length=100)),
                ('fecha', models.DateTimeField(verbose_name='Fecha cita')),
                ('motivo', models.TextField(max_length=100)),
                ('Descripcion', models.CharField(max_length=200)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.tipocita')),
            ],
        ),
    ]
