# Generated by Django 3.2.15 on 2023-09-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Citas',
            new_name='Cita',
        ),
    ]
