# Generated by Django 3.2.15 on 2023-09-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20230928_1944'),
        ('citas', '0004_detallecita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='id_cliente',
            field=models.ManyToManyField(to='clientes.Cliente', verbose_name='Cliente'),
        ),
        migrations.DeleteModel(
            name='DetalleCita',
        ),
    ]
