# Generated by Django 4.2.6 on 2023-12-10 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0006_cita_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cita",
            name="Nombre_Persona",
        ),
    ]
