# Generated by Django 4.2.6 on 2023-12-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("citas", "0007_remove_cita_nombre_persona"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="Nombre_Persona",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
