# Generated by Django 4.2.5 on 2023-10-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0003_auto_20230928_1944"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="NumDocumento",
            field=models.TextField(default="000", max_length=20),
        ),
    ]
