# Generated by Django 4.2.5 on 2023-10-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0004_cliente_numdocumento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="NumDocumento",
            field=models.TextField(default="000", max_length=20, unique=True),
        ),
    ]
