# Generated by Django 4.2.5 on 2023-10-24 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0006_alter_cliente_numdocumento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="NumDocumento",
        ),
    ]
