# Generated by Django 3.2.15 on 2023-11-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_cliente_numdocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='NumDocumento',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
