# Generated by Django 3.2.15 on 2023-09-11 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCaso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=50)),
                ('cliente', models.TextField(max_length=20)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos/casos')),
                ('estado', models.BooleanField(default=False)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.tipocaso')),
            ],
        ),
    ]
