# Generated by Django 3.2.15 on 2023-09-28 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20230928_1944'),
        ('casos', '0003_alter_caso_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caso',
            name='cliente',
        ),
        migrations.CreateModel(
            name='DetalleCaso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casos.caso')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
